server:
  port: 8763
  servlet:    context-path: /zuul

spring:
  application:
    name: zuul-server

management:  endpoints:    web:      exposure:        include: '*'

ribbon:
  ReadTimeout: 120000 # processing request time
  ConnectTimeout: 30000 # connection request time

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8762/discovery/eureka}